FROM openjdk:18-ea-11-alpine3.15

ADD target/twitter-to-kafka-service-0.0.1-SNAPSHOT.jar twitter-to-kafka-service-0.0.1-SNAPSHOT.jar

CMD ["sh", "-c", "java -jar twitter-to-kafka-service-0.0.1-SNAPSHOT.jar"]